src/main/java/org/activiti/cloud/modeling/ModelingApplication.java, src/test/java/org/activiti/cloud/modeling/ModelingApplicationTest.java
- since a new year started the copyright year was updated to 2018
refs [ #1686](https://github.com/Activiti/Activiti/issues/1686)
=> Update copyright header

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.0.11`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.0.11

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.0.12`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.0.20

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.0.21`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.0.23

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.0.24`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.0.25

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.0.26`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.0.27

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.0.28`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.0.30

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.0.31`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.0.31

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.0.32`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.0.32

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.0.33`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.0.33

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.0.34`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.0.34

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.0.35`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.0.35

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.0.36`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.0.36

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.0.37`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.0.37

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.0.38`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.0.38

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.0.39`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.0.39

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.0.40`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.0.40

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.0.41`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.0.41

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.0.44`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.0.44

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.0.45`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.0.45

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.0.47`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.0.47

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.0.48`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.0.48

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.0.49`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.0.49

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.0.51`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.0.51

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.0.53`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.0.53

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.0.55`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.0.55

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.0.56`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.0.56

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.0.57`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.0.57

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.0.58`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.0.58

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.0.59`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.0.59

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.0.60`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.0.60

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.0.61`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.0.61

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.0.62`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.0.62

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.0.63`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.0.63

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.0`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.0

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.1`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.1

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.2`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.2

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.6`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.6

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.8`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.8

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.9`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.9

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.0.64`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.0.64

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.14`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.14

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.18`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.18

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.19`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.19

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.20`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.20

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.21`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.21

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.24`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.24

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.27`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.27

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.28`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.28

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.30`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.30

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.31`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.31

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.32`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.32

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.33`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.33

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.34`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.34

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.0.66`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.0.66

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.35`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.35

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.0.67`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.0.67

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.36`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.36

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.37`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.37

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.38`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.38

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.39`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.39

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.41`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.41

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.42`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.42

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.47`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.47

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.48`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.48

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.49`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.49

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.51`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.51

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.52`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.52

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.0.68`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.0.68

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.53`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.53

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.54`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.54

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.56`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.56

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.57`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.57

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.58`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.58

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.61`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.61

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.62`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.62

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.0.69`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.0.69

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.63`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.63

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.64`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.64

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.65`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.65

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.66`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.66

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.67`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.67

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.68`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.68

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.0.70`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.0.70

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.80`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.80

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.81`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.81

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.82`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.82

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.83`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.83

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.86`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.86

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.88`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.88

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.91`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.91

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.96`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.96

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.97`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.97

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.98`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.98

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.101`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.101

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.102`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.102

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.103`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.103

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.104`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.104

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.105`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.105

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.106`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.106

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.107`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.107

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.108`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.108

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.109`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.109

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.110`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.110

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.111`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.111

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.112`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.112

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.113`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.113

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.114`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.115

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.116`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.116

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.117`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.117

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.118`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.118

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.119`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.119

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.120`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.120

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.121`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.121

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.122`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.122

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.123`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.123

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.124`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.124

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.125`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.125

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.126`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.126

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.127`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.127

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.128`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.128

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.129`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.129

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.130`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.130

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.131`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.131

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.132`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.132

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.133`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.133

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.134`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.134

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.135`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.135

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.136`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.136

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.137`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.137

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.138`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.138

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.139`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.139

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.140`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.140

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.141`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.141

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.142`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.142

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.143`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.144

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.145`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.145

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.146`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.146

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.147`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.147

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.148`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.148

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.150`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.150

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.151`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.151

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.152`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.152

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.153`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.153

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.154`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.154

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.155`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.155

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.156`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.156

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.157`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.157

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.158`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.158

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.159`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.159

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.160`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.160

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.161`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.161

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.162`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.162

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.163`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.163

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.164`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.164

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.165`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.165

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.166`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.166

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.169`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.169

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.170`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.170

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.172`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.172

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.173`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.173

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.174`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.174

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.175`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.175

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.176`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.176

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.177`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.177

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.178`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.178

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.179`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.179

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.180`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.180

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.181`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.181

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.182`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.182

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.183`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.183

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.184`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.184

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.185`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.185

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.186`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.186

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.187`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.187

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.188`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.188

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.189`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.189

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.190`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.190

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.191`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.191

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.192`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.192

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.193`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.193

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.194`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.194

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.195`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.195

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.196`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.196

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.197`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.197

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.198`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.198

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.199`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.199

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.200`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.200

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.201`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.201

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.202`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.202

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.203`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.203

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.204`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.204

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.205`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.205

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.206`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.206

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.207`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.207

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.208`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.208

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.210`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.210

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.211`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.211

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.212`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.212

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.213`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.213

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.214`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.214

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.216`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.216

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.218`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.218

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.219`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.219

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.220`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.220

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.221`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.221

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.222`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.222

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.225`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.225

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.228`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.228

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.229`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.229

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.230`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.230

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.232`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.232

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.233`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.233

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.235`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.235

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.236`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.236

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.237`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.237

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.238`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.238

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.239`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.239

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.240`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.240

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.241`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.241

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.242`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.242

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.243`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.243

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.244`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.252

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.253`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.253

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.254`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.254

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.255`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.255

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.256`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.256

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.257`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.257

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.258`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.258

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.259`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.259

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.260`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.260

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.261`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.261

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.262`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.262

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.263`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.263

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.264`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.264

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.265`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.265

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.266`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.266

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.267`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.267

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.268`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.268

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.269`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.269

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.270`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.270

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.271`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.271

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.272`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.272

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.273`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.273

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.274`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.274

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.275`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.275

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.276`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.276

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.277`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.277

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.278`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.278

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.279`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.279

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.280`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.280

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.281`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.281

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.282`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.282

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.283`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.283

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.284`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.284

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.285`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.285

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.286`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.286

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.287`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.287

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.288`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.288

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.289`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.289

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.290`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.290

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.295`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.295

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.296`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.296

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.297`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.297

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.298`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.298

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.299`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.299

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.300`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.300

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.301`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.301

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.302`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.302

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.303`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.303

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.304`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.304

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.305`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.305

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.306`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.306

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.307`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.307

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.308`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.308

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.309`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.310

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.312`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.312

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.314`
=> update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.314

charts/activiti-cloud-modeling/requirements.yaml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed helm dependency: `common` to: `1.1.28`
=> fix(versions): update Activiti/activiti-cloud-modeling versions
