Activiti/activiti-cloud-modeling

charts/activiti-cloud-modeling/Makefile
charts/activiti-cloud-modeling/values.yaml

the regex `7\.0\.[1-9]\d*$` should match 7.0.1 but not 7.0.0 though not entirely sure if the characters in it are properly escaped - does do the trick locally

only relace tag matching 7.0.non-zero

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.1`

update \s+tag: (.*) to 0.0.1

---

.updatebot.yml

for https://github.com/Activiti/Activiti/issues/2347

example just for modeling

---

pom.xml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.0.43`

update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.0.43

---

pom.xml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.0.50`

update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.0.50

---

charts/activiti-cloud-modeling/templates/deployment.yaml
charts/activiti-cloud-modeling/values.yaml

looks like Values.backend.resources  was missing

helm resources update

---

pom.xml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.0.52`

update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.0.52

---

pom.xml
src/main/java/org/activiti/cloud/modeling/ModelingApplication.java
src/test/java/org/activiti/cloud/modeling/ModelingRestIT.java

https://github.com/Activiti/Activiti/issues/2437

2437 remove dependency to process-model

---

pom.xml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.0.54`

update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.0.54

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.2`

update \s+tag: (.*) to 0.0.2

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.3`

update \s+tag: (.*) to 0.0.3

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.4`

update \s+tag: (.*) to 0.0.4

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.5`

update \s+tag: (.*) to 0.0.5

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.6`

update \s+tag: (.*) to 0.0.6

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.7`

update \s+tag: (.*) to 0.0.7

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.8`

update \s+tag: (.*) to 0.0.8

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.9`

update \s+tag: (.*) to 0.0.9

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.10`

update \s+tag: (.*) to 0.0.10

---

pom.xml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.3`

update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.3

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.11`

update \s+tag: (.*) to 0.0.11

---

pom.xml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.4`

update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.4

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.12`

update \s+tag: (.*) to 0.0.12

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.13`

update \s+tag: (.*) to 0.0.13

---

pom.xml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.5`

update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.5

---

pom.xml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.7`

update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.7

---

pom.xml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.10`

update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.10

---

pom.xml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.11`

update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.11

---

pom.xml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.13`

update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.13

---

pom.xml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.15`

update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.15

---

pom.xml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.16`

update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.16

---

Jenkinsfile

for https://github.com/Activiti/Activiti/issues/2586

delay so that github can first finish publishing chart

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.14`

update \s+tag: (.*) to 0.0.14

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.15`

update \s+tag: (.*) to 0.0.15

---

pom.xml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.17`

update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.17

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.16`

update \s+tag: (.*) to 0.0.16

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.17`

update \s+tag: (.*) to 0.0.17

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.18`

update \s+tag: (.*) to 0.0.18

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.19`

update \s+tag: (.*) to 0.0.19

---

pom.xml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.22`

update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.22

---

pom.xml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.23`

update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.23

---

pom.xml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.25`

update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.25

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.20`

update \s+tag: (.*) to 0.0.20

---

pom.xml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.26`

update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.26

---

pom.xml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.29`

update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.29

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.21`

update \s+tag: (.*) to 0.0.21

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.22`

update \s+tag: (.*) to 0.0.22

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.23`

update \s+tag: (.*) to 0.0.23

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.24`

update \s+tag: (.*) to 0.0.24

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.25`

update \s+tag: (.*) to 0.0.25

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.26`

update \s+tag: (.*) to 0.0.26

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.27`

update \s+tag: (.*) to 0.0.27

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.28`

update \s+tag: (.*) to 0.0.28

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.29`

update \s+tag: (.*) to 0.0.29

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.30`

update \s+tag: (.*) to 0.0.30

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.31`

update \s+tag: (.*) to 0.0.31

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.32`

update \s+tag: (.*) to 0.0.32

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.33`

update \s+tag: (.*) to 0.0.33

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.34`

update \s+tag: (.*) to 0.0.34

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.35`

update \s+tag: (.*) to 0.0.35

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.36`

update \s+tag: (.*) to 0.0.36

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.37`

update \s+tag: (.*) to 0.0.37

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.38`

update \s+tag: (.*) to 0.0.38

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.39`

update \s+tag: (.*) to 0.0.39

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.40`

update \s+tag: (.*) to 0.0.40

---

pom.xml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.40`

update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.40

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.41`

update \s+tag: (.*) to 0.0.41

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.42`

update \s+tag: (.*) to 0.0.42

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.43`

update \s+tag: (.*) to 0.0.43

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.44`

update \s+tag: (.*) to 0.0.44

---

pom.xml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.43`

update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.43

---

pom.xml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.44`

update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.45

---

pom.xml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.46`

update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.46

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.45`

update \s+tag: (.*) to 0.0.45

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.46`

update \s+tag: (.*) to 0.0.46

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.47`

update \s+tag: (.*) to 0.0.47

---

pom.xml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.50`

update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.50

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.48`

update \s+tag: (.*) to 0.0.48

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.49`

update \s+tag: (.*) to 0.0.49

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.50`

update \s+tag: (.*) to 0.0.50

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.51`

update \s+tag: (.*) to 0.0.51

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.52`

update \s+tag: (.*) to 0.0.52

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.53`

update \s+tag: (.*) to 0.0.53

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.54`

update \s+tag: (.*) to 0.0.55

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.56`

update \s+tag: (.*) to 0.0.56

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.57`

update \s+tag: (.*) to 0.0.57

---

pom.xml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.59`

update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.59

---

pom.xml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.60`

update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.60

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.58`

update \s+tag: (.*) to 0.0.58

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.59`

update \s+tag: (.*) to 0.0.59

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.60`

update \s+tag: (.*) to 0.0.60

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.61`

update \s+tag: (.*) to 0.0.61

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.62`

update \s+tag: (.*) to 0.0.62

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.63`

update \s+tag: (.*) to 0.0.63

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.64`

update \s+tag: (.*) to 0.0.64

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.65`

update \s+tag: (.*) to 0.0.65

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.66`

update \s+tag: (.*) to 0.0.66

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.67`

update \s+tag: (.*) to 0.0.67

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.68`

update \s+tag: (.*) to 0.0.68

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.69`

update \s+tag: (.*) to 0.0.69

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.70`

update \s+tag: (.*) to 0.0.70

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.71`

update \s+tag: (.*) to 0.0.71

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.72`

update \s+tag: (.*) to 0.0.72

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.73`

update \s+tag: (.*) to 0.0.73

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.74`

update \s+tag: (.*) to 0.0.74

---

charts/activiti-cloud-modeling/requirements.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed helm dependency: `common` to: `1.1.15`

fix(versions): update Activiti/activiti-cloud-modeling versions into master

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.75`

update \s+tag: (.*) to 0.0.75

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.76`

update \s+tag: (.*) to 0.0.76

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.77`

update \s+tag: (.*) to 0.0.77

---

pom.xml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.69`

update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.69

---

pom.xml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.70`

update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.71

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.78`

update \s+tag: (.*) to 0.0.78

---

pom.xml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.72`

update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.72

---

pom.xml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.73`

update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.73

---

pom.xml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.74`

update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.74

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `\s+tag: (.*)` to: `0.0.81`

update \s+tag: (.*) to 0.0.81

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.87`

update [\s+tag: (.*)] to 0.0.87

---

pom.xml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.75`

update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.75

---

pom.xml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.76`

update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.76

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.88`

update [\s+tag: (.*)] to 0.0.88

---

pom.xml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.77`

update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.77

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.89`

update [\s+tag: (.*)] to 0.0.89

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.90`

update [\s+tag: (.*)] to 0.0.92

---

pom.xml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.78`

update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.78

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.93`

update [\s+tag: (.*)] to 0.0.93

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.94`

update [\s+tag: (.*)] to 0.0.94

---

pom.xml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.79`

update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.79

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.95`

update [\s+tag: (.*)] to 0.0.95

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.96`

update [\s+tag: (.*)] to 0.0.96

---

pom.xml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.84`

update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.84

---

pom.xml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.85`

update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.85

---

pom.xml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.87`

update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.87

---

pom.xml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.89`

update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.89

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.97`

update [\s+tag: (.*)] to 0.0.97

---

pom.xml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.90`

update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.90

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.98`

update [\s+tag: (.*)] to 0.0.98

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.99`

update [\s+tag: (.*)] to 0.0.99

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.100`

update [\s+tag: (.*)] to 0.0.100

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.101`

update [\s+tag: (.*)] to 0.0.101

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.102`

update [\s+tag: (.*)] to 0.0.102

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.103`

update [\s+tag: (.*)] to 0.0.103

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.104`

update [\s+tag: (.*)] to 0.0.104

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.105`

update [\s+tag: (.*)] to 0.0.105

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.106`

update [\s+tag: (.*)] to 0.0.106

---

pom.xml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.0.71`

update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.0.71

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.107`

update [\s+tag: (.*)] to 0.0.107

---

pom.xml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.92`

update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.92

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.108`

update [\s+tag: (.*)] to 0.0.108

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.109`

update [\s+tag: (.*)] to 0.0.109

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.110`

update [\s+tag: (.*)] to 0.0.110

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.111`

update [\s+tag: (.*)] to 0.0.111

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.112`

update [\s+tag: (.*)] to 0.0.112

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.113`

update [\s+tag: (.*)] to 0.0.113

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.114`

update [\s+tag: (.*)] to 0.0.114

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.115`

update [\s+tag: (.*)] to 0.0.115

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.116`

update [\s+tag: (.*)] to 0.0.116

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.117`

update [\s+tag: (.*)] to 0.0.117

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.118`

update [\s+tag: (.*)] to 0.0.118

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.119`

update [\s+tag: (.*)] to 0.0.119

---

charts/activiti-cloud-modeling/requirements.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed helm dependency: `common` to: `1.1.22`

fix(versions): update Activiti/activiti-cloud-modeling versions

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.120`

update [\s+tag: (.*)] to 0.0.123

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.124`

update [\s+tag: (.*)] to 0.0.124

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.125`

update [\s+tag: (.*)] to 0.0.125

---

pom.xml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.93`

update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.95

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.126`

update [\s+tag: (.*)] to 0.0.126

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.127`

update [\s+tag: (.*)] to 0.0.127

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.128`

update [\s+tag: (.*)] to 0.0.128

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.129`

update [\s+tag: (.*)] to 0.0.129

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.130`

update [\s+tag: (.*)] to 0.0.130

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.131`

update [\s+tag: (.*)] to 0.0.131

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.132`

update [\s+tag: (.*)] to 0.0.132

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.133`

update [\s+tag: (.*)] to 0.0.133

---

pom.xml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.99`

update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.99

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.134`

update [\s+tag: (.*)] to 0.0.134

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.135`

update [\s+tag: (.*)] to 0.0.135

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.136`

update [\s+tag: (.*)] to 0.0.136

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.137`

update [\s+tag: (.*)] to 0.0.137

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.138`

update [\s+tag: (.*)] to 0.0.138

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.139`

update [\s+tag: (.*)] to 0.0.139

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.140`

update [\s+tag: (.*)] to 0.0.140

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.141`

update [\s+tag: (.*)] to 0.0.141

---

pom.xml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.0.72`

update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.0.72

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.142`

update [\s+tag: (.*)] to 0.0.142

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.143`

update [\s+tag: (.*)] to 0.0.143

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.144`

update [\s+tag: (.*)] to 0.0.144

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.146`

update [\s+tag: (.*)] to 0.0.146

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.147`

update [\s+tag: (.*)] to 0.0.147

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.148`

update [\s+tag: (.*)] to 0.0.148

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.149`

update [\s+tag: (.*)] to 0.0.149

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.150`

update [\s+tag: (.*)] to 0.0.150

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.151`

update [\s+tag: (.*)] to 0.0.151

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.152`

update [\s+tag: (.*)] to 0.0.152

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.153`

update [\s+tag: (.*)] to 0.0.153

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.154`

update [\s+tag: (.*)] to 0.0.154

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.155`

update [\s+tag: (.*)] to 0.0.155

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.156`

update [\s+tag: (.*)] to 0.0.156

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.157`

update [\s+tag: (.*)] to 0.0.157

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.158`

update [\s+tag: (.*)] to 0.0.158

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.159`

update [\s+tag: (.*)] to 0.0.159

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.160`

update [\s+tag: (.*)] to 0.0.160

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.161`

update [\s+tag: (.*)] to 0.0.161

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.162`

update [\s+tag: (.*)] to 0.0.162

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.163`

update [\s+tag: (.*)] to 0.0.163

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.164`

update [\s+tag: (.*)] to 0.0.164

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.165`

update [\s+tag: (.*)] to 0.0.165

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.166`

update [\s+tag: (.*)] to 0.0.166

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.167`

update [\s+tag: (.*)] to 0.0.167

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.168`

update [\s+tag: (.*)] to 0.0.168

---

.travis.yml

Fixes https://github.com/Activiti/Activiti/issues/2849

Update .travis.yml added cache for .m2

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.169`

update [\s+tag: (.*)] to 0.0.169

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.170`

update [\s+tag: (.*)] to 0.0.170

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.171`

update [\s+tag: (.*)] to 0.0.171

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.172`

update [\s+tag: (.*)] to 0.0.172

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.173`

update [\s+tag: (.*)] to 0.0.173

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.174`

update [\s+tag: (.*)] to 0.0.174

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.175`

update [\s+tag: (.*)] to 0.0.175

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.176`

update [\s+tag: (.*)] to 0.0.176

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.177`

update [\s+tag: (.*)] to 0.0.177

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.178`

update [\s+tag: (.*)] to 0.0.178

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.179`

update [\s+tag: (.*)] to 0.0.179

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.180`

update [\s+tag: (.*)] to 0.0.180

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.181`

update [\s+tag: (.*)] to 0.0.181

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.182`

update [\s+tag: (.*)] to 0.0.182

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.183`

update [\s+tag: (.*)] to 0.0.183

---

pom.xml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.149`

update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.149

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.184`

update [\s+tag: (.*)] to 0.0.184

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.185`

update [\s+tag: (.*)] to 0.0.185

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.186`

update [\s+tag: (.*)] to 0.0.186

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.187`

update [\s+tag: (.*)] to 0.0.187

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.188`

update [\s+tag: (.*)] to 0.0.188

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.189`

update [\s+tag: (.*)] to 0.0.189

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.190`

update [\s+tag: (.*)] to 0.0.190

---

charts/activiti-cloud-modeling/templates/deployment.yaml

ACTIVITI-3803 APP_CONFIG_BPM_HOST changed in modeling

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.191`

update [\s+tag: (.*)] to 0.0.191

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.192`

update [\s+tag: (.*)] to 0.0.192

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.193`

update [\s+tag: (.*)] to 0.0.193

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.194`

update [\s+tag: (.*)] to 0.0.194

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.195`

update [\s+tag: (.*)] to 0.0.195

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.196`

update [\s+tag: (.*)] to 0.0.196

---

pom.xml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.0.73`

update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.0.73

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.197`

update [\s+tag: (.*)] to 0.0.197

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.198`

update [\s+tag: (.*)] to 0.0.198

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.199`

update [\s+tag: (.*)] to 0.0.199

---

pom.xml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.209`

update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.209

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.200`

update [\s+tag: (.*)] to 0.0.200

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.201`

update [\s+tag: (.*)] to 0.0.201

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.202`

update [\s+tag: (.*)] to 0.0.202

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.203`

update [\s+tag: (.*)] to 0.0.203

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.204`

update [\s+tag: (.*)] to 0.0.204

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.205`

update [\s+tag: (.*)] to 0.0.205

---

pom.xml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.215`

update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.215

---

pom.xml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.217`

update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.217

---

pom.xml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.223`

update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.223

---

pom.xml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.224`

update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.224

---

pom.xml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.226`

update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.226

---

pom.xml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.234`

update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.234

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.206`

update [\s+tag: (.*)] to 0.0.206

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.207`

update [\s+tag: (.*)] to 0.0.207

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.208`

update [\s+tag: (.*)] to 0.0.208

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.209`

update [\s+tag: (.*)] to 0.0.209

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.210`

update [\s+tag: (.*)] to 0.0.210

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.211`

update [\s+tag: (.*)] to 0.0.211

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.212`

update [\s+tag: (.*)] to 0.0.212

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.213`

update [\s+tag: (.*)] to 0.0.213

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.214`

update [\s+tag: (.*)] to 0.0.214

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.215`

update [\s+tag: (.*)] to 0.0.215

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.216`

update [\s+tag: (.*)] to 0.0.216

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.217`

update [\s+tag: (.*)] to 0.0.217

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.218`

update [\s+tag: (.*)] to 0.0.218

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.219`

update [\s+tag: (.*)] to 0.0.219

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.220`

update [\s+tag: (.*)] to 0.0.220

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.221`

update [\s+tag: (.*)] to 0.0.221

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.222`

update [\s+tag: (.*)] to 0.0.222

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.223`

update [\s+tag: (.*)] to 0.0.223

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.224`

update [\s+tag: (.*)] to 0.0.224

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.225`

update [\s+tag: (.*)] to 0.0.225

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.226`

update [\s+tag: (.*)] to 0.0.226

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.227`

update [\s+tag: (.*)] to 0.0.227

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.228`

update [\s+tag: (.*)] to 0.0.228

---

pom.xml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.291`

update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.291

---

pom.xml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.292`

update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.292

---

pom.xml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.293`

update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.293

---

pom.xml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.294`

update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.294

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.229`

update [\s+tag: (.*)] to 0.0.229

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.230`

update [\s+tag: (.*)] to 0.0.230

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.231`

update [\s+tag: (.*)] to 0.0.231

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.232`

update [\s+tag: (.*)] to 0.0.232

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.233`

update [\s+tag: (.*)] to 0.0.233

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.234`

update [\s+tag: (.*)] to 0.0.234

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.235`

update [\s+tag: (.*)] to 0.0.235

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.236`

update [\s+tag: (.*)] to 0.0.236

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.237`

update [\s+tag: (.*)] to 0.0.237

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.238`

update [\s+tag: (.*)] to 0.0.238

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.239`

update [\s+tag: (.*)] to 0.0.239

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.240`

update [\s+tag: (.*)] to 0.0.240

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.241`

update [\s+tag: (.*)] to 0.0.241

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.242`

update [\s+tag: (.*)] to 0.0.242

---

pom.xml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.311`

update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.311

---

pom.xml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies` to: `7.1.313`

update org.activiti.cloud.dependencies:activiti-cloud-modeling-dependencies to 7.1.313

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.243`

update [\s+tag: (.*)] to 0.0.243

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.244`

update [\s+tag: (.*)] to 0.0.244

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.245`

update [\s+tag: (.*)] to 0.0.245

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.246`

update [\s+tag: (.*)] to 0.0.246

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.247`

update [\s+tag: (.*)] to 0.0.247

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.248`

update [\s+tag: (.*)] to 0.0.248

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.249`

update [\s+tag: (.*)] to 0.0.249

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.250`

update [\s+tag: (.*)] to 0.0.250

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.251`

update [\s+tag: (.*)] to 0.0.251

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.252`

update [\s+tag: (.*)] to 0.0.252

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.253`

update [\s+tag: (.*)] to 0.0.253

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.254`

update [\s+tag: (.*)] to 0.0.254

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.255`

update [\s+tag: (.*)] to 0.0.255

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.256`

update [\s+tag: (.*)] to 0.0.256

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.257`

update [\s+tag: (.*)] to 0.0.257

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.258`

update [\s+tag: (.*)] to 0.0.258

---

.editorconfig
.mergify.yml
.travis.yml
README.md
pom.xml

Update Spring Boot 2.1.11.RELEASE and Spring Cloud Greenwich.SR4 #3047

---

pom.xml
src/main/resources/application.properties
src/test/resources/application.properties

rename liquibase folder from org-service to modeling

[AAE-1497[ rename liquibase folder to modeling

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.259`

update [\s+tag: (.*)] to 0.0.259

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.260`

update [\s+tag: (.*)] to 0.0.260

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.261`

update [\s+tag: (.*)] to 0.0.261

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.262`

update [\s+tag: (.*)] to 0.0.262

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.263`

update [\s+tag: (.*)] to 0.0.263

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.264`

update [\s+tag: (.*)] to 0.0.264

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.265`

update [\s+tag: (.*)] to 0.0.265

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.266`

update [\s+tag: (.*)] to 0.0.266

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.267`

update [\s+tag: (.*)] to 0.0.267

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.268`

update [\s+tag: (.*)] to 0.0.268

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.270`

update [\s+tag: (.*)] to 0.0.270

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.271`

update [\s+tag: (.*)] to 0.0.271

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.272`

update [\s+tag: (.*)] to 0.0.272

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.273`

update [\s+tag: (.*)] to 0.0.273

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.274`

update [\s+tag: (.*)] to 0.0.274

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.275`

update [\s+tag: (.*)] to 0.0.275

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.276`

update [\s+tag: (.*)] to 0.0.276

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.277`

update [\s+tag: (.*)] to 0.0.277

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.278`

update [\s+tag: (.*)] to 0.0.278

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.279`

update [\s+tag: (.*)] to 0.0.279

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.280`

update [\s+tag: (.*)] to 0.0.280

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.281`

update [\s+tag: (.*)] to 0.0.281

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.282`

update [\s+tag: (.*)] to 0.0.282

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.283`

update [\s+tag: (.*)] to 0.0.283

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.284`

update [\s+tag: (.*)] to 0.0.284

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.285`

update [\s+tag: (.*)] to 0.0.285

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.286`

update [\s+tag: (.*)] to 0.0.286

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.287`

update [\s+tag: (.*)] to 0.0.287

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.288`

update [\s+tag: (.*)] to 0.0.288

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.289`

update [\s+tag: (.*)] to 0.0.289

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.290`

update [\s+tag: (.*)] to 0.0.290

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.291`

update [\s+tag: (.*)] to 0.0.291

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.292`

update [\s+tag: (.*)] to 0.0.292

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.293`

update [\s+tag: (.*)] to 0.0.293

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.294`

update [\s+tag: (.*)] to 0.0.294

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.295`

update [\s+tag: (.*)] to 0.0.295

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.296`

update [\s+tag: (.*)] to 0.0.296

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.297`

update [\s+tag: (.*)] to 0.0.298

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.299`

update [\s+tag: (.*)] to 0.0.299

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.300`

update [\s+tag: (.*)] to 0.0.300

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.301`

update [\s+tag: (.*)] to 0.0.301

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.302`

update [\s+tag: (.*)] to 0.0.302

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.303`

update [\s+tag: (.*)] to 0.0.303

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.304`

update [\s+tag: (.*)] to 0.0.304

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.305`

update [\s+tag: (.*)] to 0.0.305

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.306`

update [\s+tag: (.*)] to 0.0.307

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.308`

update [\s+tag: (.*)] to 0.0.308

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.309`

update [\s+tag: (.*)] to 0.0.309

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.310`

update [\s+tag: (.*)] to 0.0.310

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.311`

update [\s+tag: (.*)] to 0.0.311

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.312`

update [\s+tag: (.*)] to 0.0.312

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.313`

update [\s+tag: (.*)] to 0.0.313

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.314`

update [\s+tag: (.*)] to 0.0.314

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.315`

update [\s+tag: (.*)] to 0.0.315

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.316`

update [\s+tag: (.*)] to 0.0.316

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.317`

update [\s+tag: (.*)] to 0.0.317

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.318`

update [\s+tag: (.*)] to 0.0.318

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.319`

update [\s+tag: (.*)] to 0.0.319

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.321`

update [\s+tag: (.*)] to 0.0.321

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.322`

update [\s+tag: (.*)] to 0.0.322

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.323`

update [\s+tag: (.*)] to 0.0.323

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.324`

update [\s+tag: (.*)] to 0.0.324

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.325`

update [\s+tag: (.*)] to 0.0.325

---

charts/activiti-cloud-modeling/values.yaml

[UpdateBot](https://github.com/jenkins-x/updatebot) pushed regex: `[\s+tag: (.*)]` to: `0.0.326`

update [\s+tag: (.*)] to 0.0.326
